#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Translate misc-config.sgml text content to Simplified Chinese."""
import re

src = r"C:/Users/荷塘月色/AppData/Local/Temp/pgpool2-full/doc-zh/src/sgml/misc-config.sgml"

with open(src, "r", encoding="utf-8") as f:
    content = f.read()

# Each entry: (original_english_fragment, simplified_chinese_fragment)
# Fragments are kept small enough to avoid accidental matches.
pairs = [
    # Title
    ("Misc Configuration Parameters", "杂项配置参数"),

    # --- relcache_expire ---
    ("Specifies the relation cache expiration time in seconds.",
     "指定关系缓存的过期时间（秒）。"),
    ("The relation cache is used for caching the query result of",
     "关系缓存用于缓存查询结果，该查询结果是"),
    (" system catalogs that is used by <productname>Pgpool-II",
     "<productname>PostgreSQL</productname> 的系统目录，<productname>Pgpool-II</productname> 通过它获取包括表结构在内的各种信息"),
    (" to get various information including the table",
     ""),
    (" structures and to check table types(e.g. To check if the referred",
     "并检查表类型（例如，检查被引用的表是否为临时表）。缓存存储在"),
    (" table is a temporary table or not). The cache is maintained in",
     "<productname>Pgpool-II</productname> 子进程的本地内存空间中，其生命周期与子进程相同。如果启用了 <xref linkend=\"guc-enable-shared-relcache\">，缓存还会保存在共享内存中以在子进程间共享。"),
    (" the local memory space of <productname>Pgpool-II</productname>",
     ""),
    (" child process and its lifetime is same as of the child process.",
     ""),
    (" processes,if enable  <xref linkend=\"guc-enable-shared-relcache\">.",
     ""),
    (" So If the table is modified using <command>ALTER TABLE</command>",
     "因此，如果使用 <command>ALTER TABLE</command> 或其他方式修改了表，关系缓存将变得不一致。"),
    (" or some other means, the relcache becomes inconsistent.",
     ""),
    (" For this purpose, <varname>relcache_expire</varname> controls",
     "为此，<varname>relcache_expire</varname> 控制缓存的生命周期。默认值为 0，表示缓存永不过期。"),
    (" the life time of the cache.",
     ""),
    (" Default is 0, which means the cache never expires.",
     ""),
    ("This parameter can only be set at server start.",
     "此参数只能在服务器启动时设置。"),

    # --- relcache_size ---
    ("Specifies the number of relcache entries. Default is 256.",
     "指定 relcache 条目的数量。默认为 256。"),
    (" The cache is created  about 10 entries per table. So you can estimate",
     "每个表大约创建 10 个缓存条目。因此可以按「使用表数量 × 10」来估算所需的关系缓存大小。"),
    (" the required number of relation cache at \"number of using table * 10\".",
     ""),
    ("If the below message frequently appears in the",
     "如果以下消息在"),
    ("<productname>Pgpool-II</productname> log, you may need to",
     "<productname>Pgpool-II</productname> 日志中频繁出现，则可能需要增大 <varname>relcache_size</varname> 以改善性能。"),
    (" increase the <varname>relcache_size</varname> for better performance.",
     ""),

    # --- enable_shared_relcache ---
    ("By setting to on, relation cache is shared among",
     "设置为 on 后，关系缓存将在"),
    (" child processes using the in",
     "<productname>Pgpool-II</productname> 子进程间通过内存查询缓存共享（详见"),
    (" memory query cache (see <xref",
     "<xref linkend=\"runtime-in-memory-query-cache-enabling\">）。默认为 on。每个子进程都需要访问"),
    (" linkend=\"runtime-in-memory-query-cache-enabling\"> for more",
     "<productname>PostgreSQL</productname> 的系统目录。启用此功能后，其他进程可以从查询缓存中提取目录查找结果，从而降低查询频率。即使修改了系统目录，缓存也不会自动失效，因此强烈建议配合使用 <xref linkend=\"guc-relcache-expire\"> 参数设置基于超时的缓存失效机制。"),
    (" details). Default is on. Each child process needs to access to",
     ""),
    (" the system catalog from <productname>PostgreSQL</productname>.",
     ""),
    (" By enabling this feature, other process can extract the catalog",
     ""),
    (" lookup result from the query cache and it should reduce the",
     ""),
    (" frequency of the query. Cache invalidation is not happen even if",
     ""),
    (" the system catalog is modified. So it is strongly recommend to",
     ""),
    (" set time out base cache invalidation by using <xref",
     ""),
    (" linkend=\"guc-relcache-expire\"> parameter.",
     ""),
    ("This parameter can be used even if <xref",
     "即使 <xref"),
    (" linkend=\"guc-memory-cache-enabled\"> is off.  In this case some",
     " linkend=\"guc-memory-cache-enabled\"> 为 off，此参数仍可使用。此时会一并使用某些查询缓存参数（<xref linkend=\"guc-memqcache-method\">、<xref linkend=\"guc-memqcache-maxcache\"> 及各缓存存储参数）。"),
    (" query cache parameters(<xref linkend=\"guc-memqcache-method\">,",
     ""),
    (" linkend=\"guc-memqcache-maxcache\"> and each cache storage",
     ""),
    (" parameter) is used together.",
     ""),
    ("<productname>Pgpool-II</productname> search the local relation",
     "<productname>Pgpool-II</productname> 首先搜索本地关系缓存。如果在本地缓存中未找到，且此功能已启用，则会搜索共享关系查询缓存。如果在查询缓存中找到，则将其复制到本地关系缓存中。如果在任何地方都未找到缓存条目，"),
    (" cache first. If it is not found on the cache, the shared relation",
     ""),
    (" query cache is searched if this feature is enabled. If it is",
     ""),
    (" found on query cache, it is copied into the local relation",
     ""),
    (" cache. If a cache entry is not found on anywhere,",
     ""),
    (" <productname>Pgpool-II</productname> executes the query against",
     "<productname>Pgpool-II</productname> 将向 <productname>PostgreSQL</productname> 执行查询，并将结果存储到共享关系缓存和本地缓存中。"),
    (" <productname>PostgreSQL</productname>, and the result is stored",
     ""),
    (" into the shared relation cache and the local cache.",
     ""),

    # --- relcache_query_target ---
    ("The target node to send queries to create relation cache",
     "创建关系缓存条目时发送查询的目标节点。如果设置为 <literal>primary</literal>，查询将发送到主节点。这是默认值，也是大多数用户推荐的选择，因为查询可以获取最新信息。如果要降低主节点的负载，可以将参数设置为 <literal>load_balance_node</literal>，将查询发送到负载均衡节点。对于 <productname>Pgpool-II</productname>/主服务器位于 A 大陆而其他 <productname>Pgpool-II</productname>/备服务器位于 B 大陆的系统，这一选项尤其有用。B 大陆的客户端希望从备库读取数据，因为它地理位置更近。此时可将 backend_weight0（代表主节点）设为 0，backend_weight1（代表备节点）设为 1，并将 relcache_query_target 设置为 <literal>load_balance_node</literal>。"),
    (" entries. If set to <literal>primary</literal>, queries will",
     ""),
    (" be sent to primary node. This is the default and",
     ""),
    (" recommended to most users because the query could get the",
     ""),
    (" latest information.  If you want to lower the load of",
     ""),
    (" primary node, you can set the parameter to",
     ""),
    (" <literal>load_balance_node</literal>, which will send",
     ""),
    (" queries to the load balance node. This is especially useful",
     ""),
    (" for such a system",
     ""),
    (" where <productname>Pgpool-II</productname>/primary server is",
     ""),
    (" on a continent A while",
     ""),
    (" other <productname>Pgpool-II</productname>/standby server is",
     ""),
    (" on other continent B. Clients on B want read data from the",
     ""),
    (" standby because it's much geographically closer. In this",
     ""),
    (" case you can set backend_weight0 (this represents primary)",
     ""),
    (" to 0, backend_weight1 to 1 (this represents standby) and set",
     ""),
    (" relcache_query_target",
     ""),
    (" to <literal>load_balance_node</literal>.",
     ""),
    ("Note, however, if you send query to the standby node,",
     "需要注意的是，如果向备节点发送查询，由于复制延迟，刚创建的表和行在备服务器上可能还不可用。因此，对于数据修改活动频繁的系统，不建议采用这种配置。"),
    (" recently created tables and rows might not be available on",
     ""),
    (" the standby server yet because of replication delay. Thus",
     ""),
    (" such a configuration is not recommended for systems where",
     ""),
    (" data modification activity is high.",
     ""),
    ("This parameter can be changed by reloading",
     "通过重新加载"),
    (" the <productname>Pgpool-II</> configurations.",
     "<productname>Pgpool-II</productname> 配置可以更改此参数。"),

    # --- check-temp-table ---
    ("Setting to <literal>catalog</literal>",
     "设置为 <literal>catalog</literal>"),
    (" or <literal>trace</literal>, enables the temporary table",
     " 或 <literal>trace</literal>，可启用 <acronym>SELECT</acronym> 语句中的临时表检查。"),
    (" check in the <acronym>SELECT</acronym> statements. To check",
     "如需检查临时表，<productname>Pgpool-II</productname> 会查询主 <productname>PostgreSQL</productname> 后端的系统目录（当指定 <literal>catalog</literal> 时），这会增加主服务器的负载。"),
    (" the temporary table <productname>Pgpool-II</productname>",
     ""),
    (" queries the system catalog of",
     ""),
    (" primary/main <productname>PostgreSQL</productname> backend",
     ""),
    (" if <literal>catalog</literal> is specified, which",
     ""),
    (" increases the load on the primary/main server.",
     ""),
    ("If <literal>trace</literal> is",
     "如果设置为 <literal>trace</literal>，<productname>Pgpool-II</productname> 会跟踪临时表的创建和删除操作以获取临时表信息，因此无需访问系统目录。但是，如果临时表的创建对 <productname>Pgpool-II</productname> 不可见（例如在函数或触发器中完成），则 <productname>Pgpool-II</productname> 无法识别临时表的创建。"),
    (" set, <productname>Pgpool-II</productname> traces temporary",
     ""),
    (" table creation and dropping to obtain temporary table",
     ""),
    (" info. So no need to access system catalogs. However, if",
     ""),
    (" temporary table creation is invisible",
     ""),
    (" to <productname>Pgpool-II</productname> (done in functions",
     ""),
    (" or triggers, for",
     ""),
    (" example), <productname>Pgpool-II</productname> cannot",
     ""),
    (" recognize the creation of temporary tables.",
     ""),
    ("If you are absolutely sure that your system never uses",
     "如果您确定系统中永远不会使用临时表，则可以安全地设置为 none。"),
    (" temporary tables, then you can safely set to none.",
     ""),
    ("For a backward compatibility sake for 4.0 or",
     "为兼容 4.0 及更早版本，<productname>Pgpool-II</productname> 接受 <literal>on</literal>（与 <literal>catalog</literal> 相同）和 <literal>off</literal>（与 <literal>none</literal> 相同），它们可能会在未来的版本中被删除。"),
    (" before, <productname>Pgpool-II</productname>",
     ""),
    (" accepts <literal>on</literal>, which is same",
     ""),
    (" as <literal>catalog</literal> and <literal>off</literal>,",
     ""),
    (" which is same as <literal>none</literal>, they may be",
     ""),
    (" deleted in the future version.",
     ""),
    ("Default is <literal>catalog</literal>.",
     "默认为 <literal>catalog</literal>。"),
    ("This parameter can be changed by reloading",
     "通过重新加载"),
    (" the <productname>Pgpool-II</productname> configurations.",
     "<productname>Pgpool-II</productname> 配置可以更改此参数。"),
    (" You can also use <xref linkend=\"SQL-PGPOOL-SET\"> command to",
     "您也可以使用 <xref linkend=\"SQL-PGPOOL-SET\"> 命令在当前会话中更改此参数的值。"),
    (" alter the value of this parameter for a current session.",
     ""),

    # --- check-unlogged-table ---
    ("Setting to on, enables the unlogged table check in the <acronym>SELECT</acronym>",
     "设置为 on，可启用 <acronym>SELECT</acronym> 语句中的未记录表检查。"),
    (" statements. To check the unlogged table <productname>Pgpool-II</productname>",
     "如需检查未记录表，<productname>Pgpool-II</productname> 会查询主 <productname>PostgreSQL</productname> 后端的系统目录，这会增加主服务器的负载。"),
    (" queries the system catalog of primary/main <productname>PostgreSQL</> backend which increases",
     ""),
    (" the load on the primary/main server.",
     "如果您确定系统中永远不会使用未记录表（例如，您使用的是 9.0 或更早版本的 <productname>PostgreSQL</productname>），则可以安全地关闭 <varname>check_unlogged_table</varname>。默认为 on。"),
    ("If you are absolutely sure that your system never uses the unlogged tables",
     ""),
    (" (for example, you are using 9.0 or earlier version of <productname>PostgreSQL</>) then you",
     ""),
    (" can safely turn off the <varname>check_unlogged_table</varname>.",
     ""),
    (" Default is on.",
     ""),
    ("This parameter can be changed by reloading the <productname>Pgpool-II</> configurations.",
     "通过重新加载 <productname>Pgpool-II</productname> 配置可以更改此参数。"),
    (" You can also use <xref linkend=\"SQL-PGPOOL-SET\"> command to alter the value of",
     "您也可以使用 <xref linkend=\"SQL-PGPOOL-SET\"> 命令在当前会话中更改此参数的值。"),
    ("  this parameter for a current session.",
     ""),

    # --- pid-file-name ---
    ("Specifies the full path to a file to store the <productname>Pgpool-II",
     "指定用于存储 <productname>Pgpool-II</productname> 进程 ID 的文件完整路径。"),
    (" </productname> process id.",
     ""),
    (" The pid_file_name path can be specified as relative to the",
     "pid_file_name 路径可以相对于 pgpool.conf 文件位置指定，也可以使用绝对路径。默认为 <literal>/var/run/pgpool/pgpool.pid</literal>。"),
    (" location of pgpool.conf file or as an absolute path",
     ""),
    (" Default is <literal>\"/var/run/pgpool/pgpool.pid\"</literal>.",
     ""),

    # --- work-dir ---
    ("Specifies the full path to a directory to store the <literal>pgpool_status</literal>.",
     "指定用于存储 <literal>pgpool_status</literal> 的目录完整路径。默认为 <literal>/tmp</literal>。"),
    (" Default is <literal>'/tmp'</literal>.",
     ""),

    # --- health-check-test ---
    ("Do not set this parameter to on in a production",
     "请勿在生产环境中将此参数设置为 on。此功能仅用于测试目的。"),
    (" environment. This feature is purely for testing purpose.",
     ""),
    ("Setting to on,",
     "设置为 on 后，可启用健康检查的测试功能。在这种情况下，健康检查进程会查看 <xref linkend=\"guc-work-dir\"> 下的 <filename>backend_down_request</filename> 文件。该文件可能包含多行，每行对应一个后端。文件中的行以后端 ID 开头（必须是从小数 0 开始的十进制数），接着是一个 TAB，最后以 \"down\" 结尾。后端被假定为宕机状态，<productname>Pgpool-II</productname> 将启动故障转移。故障转移完成后，健康检查进程会将 \"down\" 改写为 \"already_down\" 以防止重复故障转移。"),
    (" enables the testing facility of health checking. In this case the",
     ""),
    (" health check process looks",
     ""),
    (" into <filename>backend_down_request</filename>",
     ""),
    (" under <xref linkend=\"guc-work-dir\">.  The file may contain multiple",
     ""),
    (" lines, and each line corresponds to each backend. A line in the",
     ""),
    (" file starts with backend id (must be a decimal number starting",
     ""),
    (" with zero), then a TAB, and ends with \"down\". The backend is",
     ""),
    (" assumed in down status and <productname>Pgpool-II</productname>",
     ""),
    (" will start a failover. Once the failover completes, the \"down\" is",
     ""),
    (" rewritten to \"already_down\" by health check process to prevent",
     ""),
    (" repeating failovers.",
     ""),
    ("This feature is particularly useful for",
     "此功能对测试 <xref linkend=\"guc-failover-require-consensus\"> 非常有用。假设我们有 3 个 watchdog 节点，每个 watchdog 检查后端 0 的健康状况。只在 watchdog 0 下的文件中设置 \"0\tdown\"，其他 watchdog 将不认同后端 0 不健康，因此不会发生故障转移。使用此功能可以模拟此类部分网络故障。"),
    (" testing <xref linkend=\"guc-failover-require-consensus\">. Suppose",
     ""),
    (" we have 3 watchdog node. Each watchdog checks healthiness of",
     ""),
    (" backend 0. By setting \"0\tdown\" in the file only under watchdog 0,",
     ""),
    (" other watchdogs disagree with the unhealthiness of backend 0, so",
     ""),
    (" failover will not occur. This kind of partial network failure can",
     ""),
    (" be simulated using this feature.",
     ""),
    ("Default is <literal>off</literal>.",
     "默认为 <literal>off</literal>。"),
]

for old, new in pairs:
    if old not in content:
        print(f"WARNING: not found: {old!r}")
    content = content.replace(old, new)

# Fix stray </> tags left from source
content = content.replace("</>", "</productname>")

with open(src, "w", encoding="utf-8", newline="") as f:
    f.write(content)

print("Translation complete.")
